########################################
# Load config and variables
########################################

configfile: "../config/config.yaml"
PROJECT = config["project"]["name"]
OUTDIR = config["project"]["output_dir"]
SAMPLES = [row.split("\t")[0] for row in open(config["samples"]) if not row.startswith("sample")]


########################################
# Include rule modules
########################################

include: "rules/uncompress.snakefile"
include: "rules/trim.snakefile"
include: "rules/quality_control.snakefile"
include: "rules/align_kallisto.snakefile"
include: "rules/align_HiSat2.snakefile"
include: "rules/spladder_run.snakefile"
include: "rules/bisbee_run.snakefile"
include: "rules/interproscan_run.snakefile"

########################################
# Final targets
########################################

rule all:
    input:
        expand(f"{OUTDIR}/{PROJECT}/final/{sample}.done", sample=SAMPLES)
