name: Pipeline
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - snakemake=7.19.1
  - r-tinytex=0.43
  - r-base=4.2.1
  - python=3.11.0
  - r-rmarkdown=2.19
  - r-curl=4.3.3
  - fastqc=0.11.9
  - qualimap=2.2.2d
  - multiqc=1.13
  - kallisto=0.48.0
  - gzip=1.12
  - hisat2=2.2.1
  - bioconductor-biobase=2.58.0
  - bioconductor-biocgenerics=0.44.0
  - bioconductor-biocio=1.8.0
  - bioconductor-biocparallel=1.32.0
  - bioconductor-biostrings=2.66.0
  - bioconductor-genomicalignments
  - bioconductor-genomicranges=1.50.0
  - bioconductor-iranges=2.32.0
  - bioconductor-matrixgenerics=1.10.0
  - bioconductor-rtracklayer=1.58.0
  - numpy=1.24.1
  - pandas=1.5.2
  - pip=22.3.1
  - pyensembl
  - samtools=1.16.1
  - stringtie=2.2.1
  - pip:
    - spladder==2.4.3
    - bio==1.5.3
