name: Pipeline
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - snakemake=5.3.0
  - graphviz=2.40.1
# command tool installs
  - R=3.6.0
  - python=3.8.1
  - pip
  - interproscan 
# r channel installs
#  - r-yaml=2.2.0
#  - r-statmod=1.4.30
#  - r-gplots=3.0.1
  - r-rmarkdown
  - r-magrittr
# conda-forge channel installs
#  - r-heatmap.plus=1.3
#  - r-readr=1.3.1
# bioconda channel installs
  - fastqc=0.11.8
  - qualimap=2.2.2
  - multiqc
  - kallisto=0.46.1
  - hisat2= 2.2.1
##  - subread=1.6.4  # featureCounts included
  - stringtie=2.2.1
#  - htseq=0.11.2  # htseq-count included
#  - bioconductor-mygene=1.18.0
#  - bioconductor-tximport=1.12.1
#  - bioconductor-enhancedvolcano=1.2.0
  - bioconductor-biomart
  - pip:
    - spladder==2.4.3
#    - numpy==1.16.6
    - pyensembl
    - Bio
#export LANG=en_US.utf-8
#export LC_ALL=UTF-8
