name: Pipeline_newestR
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - snakemake=7.19.1
  - graphviz
  - r-tinytex
# command tool installs
  - r-base=4.2.1
  - python
  - pip
#  - interproscan
# r channel installs
#  - r-yaml=2.2.0
#  - r-statmod=1.4.30
#  - r-gplots=3.0.1
  - r-rmarkdown
  - r-curl
# #  - r-magrittr
# # bioconda channel installs
  - fastqc=0.11
  - qualimap=2.2.2
  - multiqc
  - kallisto=0.48
  - hisat2= 2.2.1
  - stringtie=2.2.1
  - pyensembl
# #   - bioconductor-biomart
  - bioconductor-rtracklayer
  - pip:
    - spladder==2.4.3
    - numpy
  #  - pyensembl
    - Bio
    - pandas
#export LANG=en_US.utf-8
#export LC_ALL=UTF-8
