# Project metadata
project:
  name: my_project
  output_dir: results

input:
  samples: Test_data/samples.tsv
  compression: gz

# References
reference:
  genome_fasta: Test_data/Mus_musculus.GRCm39.dna.toplevel.fa
  annotation_gtf: Test_data/Mus_musculus.GRCm39.115.gtf
  transcriptome_fasta: Test_data/Mus_musculus.GRCm39.all.fa

sequencing:
  layout: paired # single | paired

# Tools
trimming:
  enabled: true
  threads: 4

alignment:
  method: hisat2 # hisat2 | kallisto
  threads: 8

spladder:
  enabled: false

bisbee:
  enabled: false
  ensembl_release: 104

interproscan:
  enabled: false

# Differential expression
dge:
  enabled: true
  contrast: "B1_treated - B1_control"
  group1: "treated"
  group2: "control"
  p_value: 0.05
  go_threshold: 0.05
  go_mapping: org.Mm.eg.db
  sva.enabled: False

# Alternative splicing
ase:
  enabled: true
