# Please check the parameters, and adjust them according to your circumstance

# project name
PROJECT: Test

## the path to fastq files

INPUTPATH: /home/agata/Documents/Work/Pipeline/Test_data

## the meta file describing the experiment settings
METAFILE: configs/Description.csv

## paths for intermediate and final outputs
FINALOUTPUT: /home/agata/Documents/Work/Pipeline/Output

## is the sequencing paired-end or pair-end?
END: "single"  # "single" or "pair"?

## is input uncompressed
COMPRESSION_TYPE: "dsrc" # "none", "gz", "dsrc"

#switch to no if trimming was not performed
TRIMMED: "yes"

## transcriptome file
TRANS: /home/agata/Documents/Work/Pipeline/Test_data/Mus_musculus.GRCm38.cdna.all.fa

## genome and annotation files
GENOME:  /home/agata/Documents/Work/Pipeline/Test_data/Mus_musculus.GRCm39.dna.toplevel.fa
ANNOTATION: /home/agata/Documents/Work/Dell_work/bisbee/Mus_musculus.GRCm39.104.gtf
ATTRIBUTE: gene_id  # the attribute used in annotation file. It's usually "gene_id", but double check that since it may also be "gene", "ID"...

## number of cores
NCORE: 9

## Bisbbe path
BB_PATH : ./scripts/bisbee
## Desired release for bisbee
RELEASE: 104

#Thresholds for Spladder analysis with Rmarkdown
#For Spladder, HiSat and Kallisto define organism
DATSET_MART: mmusculus_gene_ensembl #  e.g. do: mart = useMart('ensembl') then listDatasets(mart, verbose = FALSE) for others
GO_MAPPING: org.Mm.eg.db # OrganismDb or OrgDb annotation package from Bioconductor

TH_SAMPLES: 4 # How many samples should pass the condition
TH_STD: 0.2
TH_PSI: 0.1
TH_GO: 0.01

#BAM file for events visualization- either for particular sample or concatenated BAM (must be indexed!)
BAM: /home/agata/Documents/Work/Pipeline_old/Output/Test/genome/bamFileSort/CMV_PNSL_10.1.sort.bam

## InterProScan path
IP_PATH: /home/agata/Documents/Work/InterPro/interproscan-5.55-88.0

#For differential expression- define which groups to check
#HiSat
CONTRAST_HiSat: B1_CMV_PNSLvsB1_CMV_SHAM=B1_CMV_SHAM-B1_WTP_SHAM
P_VAL_HiSat: 0.05
TH_GO_HiSat: 0.01

#Kallisto
CONTRAST_kallisto: B1_CMV_PNSLvsB1_CMV_SHAM=B1_CMV_SHAM-B1_WTP_SHAM
P_VAL_kallisto: 0.05
TH_GO_kallisto: 0.01
