# Please check the parameters, and adjust them according to your circumstance

# project name
PROJECT: Test

## the path to fastq files

INPUTPATH: /home/agata/Documents/Work/Pipeline/Test_data

## the meta file describing the experiment settings
METAFILE: configs/Description.csv

## paths for intermediate and final outputs
FINALOUTPUT: /home/agata/Documents/Work/Pipeline/Output

## is the sequencing paired-end or pair-end?
END: "single"  # "single" or "pair"?

## is input uncompressed
COMPRESSED: "yes" # "yes" or "no"

## transcriptome file
TRANS: /home/agata/Documents/Work/Pipeline/Test_data/Mus_musculus.GRCm38.cdna.all.fa

## genome and annotation files
GENOME:  /home/agata/Documents/Work/Pipeline/Test_data/Mus_musculus.GRCm39.dna.toplevel.fa
ANNOTATION: /home/agata/Documents/Work/Dell_work/bisbee/Mus_musculus.GRCm39.104.gtf
ATTRIBUTE: gene_id  # the attribute used in annotation file. It's usually "gene_id", but double check that since it may also be "gene", "ID"...

## number of cores
NCORE: 6

## aligner Hisat2/Kallisto
ALIGNER: Hisat2

## tool for feature count
COUNTER: StringTie


## Bisbbe path
BB_PATH : /home/agata/Documents/Work/Pipeline/scripts/bisbee
## Desired release for bisbee
RELEASE: 104

TH_SAMPLES: 4
TH_STD: 0.2
TH_PSI: 0.1
TH_GO: 0.01

## analyse proteins?
InterPro: "yes"
## InterProScan path
IP_PATH: /home/agata/Documents/Work/InterPro/interproscan-5.55-88.0
